# Generated by Django 4.2.7 on 2023-11-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(max_length=8)),
                ('data_type', models.CharField(max_length=16)),
                ('data_value', models.CharField(max_length=256)),
            ],
        ),
    ]
