# Generated by Django 4.2.7 on 2023-11-27 18:23

import csv_validation.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_validation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='data_value',
            field=models.CharField(max_length=256, validators=[csv_validation.validators.data_type_validator]),
        ),
    ]
